// <auto-generated />
using System;
using EstateAggregator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EstateAggregator.Data.Migrations
{
    [DbContext(typeof(EstateDbContext))]
    partial class EstateDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("EstateAggregator.Models.AppSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvailabilityText")
                        .HasColumnType("TEXT");

                    b.Property<string>("DistrictsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastScrapedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxPagesPerSource")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PriceMax")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("PriceMin")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("RoomsMax")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoomsMin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ScrapeCaixaImobiliarioEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ScrapeCasaSapoEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ScrapeIdealistaEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ScrapeImoVirtualEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ScrapeImobiliarioEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ScrapeSantanderEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SenderName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("EstateAggregator.Models.CommHistoryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MyListingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subject")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("MyListingId");

                    b.ToTable("CommHistoryEntries");
                });

            modelBuilder.Entity("EstateAggregator.Models.MyListing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentName")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentPhone")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AskedAboutOpenPlanKitchen")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AskedAboutOrientation")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FollowUpDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("PropertyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("MyListings");
                });

            modelBuilder.Entity("EstateAggregator.Models.PriceHistoryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NewPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("OldPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("PropertyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("PriceHistoryEntries");
                });

            modelBuilder.Entity("EstateAggregator.Models.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentName")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentPhone")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Baths")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Beds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConstructionStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DedupHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Elevator")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FirstScrapedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Lat")
                        .HasColumnType("REAL");

                    b.Property<double?>("Lng")
                        .HasColumnType("REAL");

                    b.Property<string>("LocationString")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("OpenPlanKitchen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrientationSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Parking")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhotosJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("SizeM2")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourcePropertyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SunOrientation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Beds");

                    b.HasIndex("DedupHash");

                    b.HasIndex("LastSeenAt");

                    b.HasIndex("LocationString");

                    b.HasIndex("Price");

                    b.HasIndex("Source");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("EstateAggregator.Models.PropertySource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("PropertyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("Url");

                    b.ToTable("PropertySources");
                });

            modelBuilder.Entity("EstateAggregator.Models.ScraperRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasErrors")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PropertiesAdded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PropertiesFound")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PropertiesLinked")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PropertiesSkipped")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PropertiesUpdated")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RunEndTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RunStartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunStartTime");

                    b.HasIndex("Source");

                    b.ToTable("ScraperRuns");
                });

            modelBuilder.Entity("EstateAggregator.Models.CommHistoryEntry", b =>
                {
                    b.HasOne("EstateAggregator.Models.MyListing", "MyListing")
                        .WithMany("CommHistory")
                        .HasForeignKey("MyListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MyListing");
                });

            modelBuilder.Entity("EstateAggregator.Models.MyListing", b =>
                {
                    b.HasOne("EstateAggregator.Models.Property", "Property")
                        .WithOne("MyListing")
                        .HasForeignKey("EstateAggregator.Models.MyListing", "PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("EstateAggregator.Models.PriceHistoryEntry", b =>
                {
                    b.HasOne("EstateAggregator.Models.Property", "Property")
                        .WithMany("PriceHistory")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("EstateAggregator.Models.PropertySource", b =>
                {
                    b.HasOne("EstateAggregator.Models.Property", "Property")
                        .WithMany("LinkedSources")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("EstateAggregator.Models.MyListing", b =>
                {
                    b.Navigation("CommHistory");
                });

            modelBuilder.Entity("EstateAggregator.Models.Property", b =>
                {
                    b.Navigation("LinkedSources");

                    b.Navigation("MyListing");

                    b.Navigation("PriceHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
